name: Free-RDP-NoCard

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: ğŸ” Enable RDP & Create User
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user iceyy qwe123zx /add
          net localgroup administrators iceyy /add

      - name: ğŸŒ©ï¸ Install Cloudflared
        run: |
          iwr -outf cloudflared.exe https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe

      - name: ğŸšª Start Tunnel
        run: |
          Start-Process cloudflared.exe -ArgumentList "tunnel --url rdp://localhost:3389" -NoNewWindow

      - name: ğŸ“‹ Show Login Info
        run: |
          echo ğŸŒ
